server:
  port: 9902

spring:
  profiles:
    include: eureka
  thymeleaf:
    cache: false
    prefix:
      classpath: /templates
    mode: LEGACYHTML5
security:
  user:
    name: ingage
    password: admin
logging:
  level: warn

zkManager:
  DefaultZookeeperConnectionManager
discoveryManager:
  DefaultDiscoveryConnectionManager
